import "./globals.css";
import "@repo/ui/styles.css";
import "@repo/shells/styles.css";
import "@repo/viz/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppShell } from "@repo/ui/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

// Menu items.
const items = [
  {
    title: "Home",
    url: "#",
    icon: "Home",
  },
  {
    title: "Inbox",
    url: "#",
    icon: "Inbox",
  },
  {
    title: "Calendar",
    url: "#",
    icon: "Calendar",
  },
  {
    title: "Search",
    url: "#",
    icon: "Search",
  },
  {
    title: "Settings",
    url: "#",
    icon: "Settings",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppShell items={items}>{children}</AppShell>
      </body>
    </html>
  );
}
